#!/usr/bin/python3
import boto3

s3 = boto3.client('s3')
def s3_upload():
	bucket = input('Which bucket do you wish to use? ')
	oldname = input('What is the name of the file to upload? ')
	newname = input('What do you want to call the file? ')
	s3.upload_file(oldname,bucket,newname)
s3_upload()
